### ISSUE TITLE
Upcoming release - IBM COS Resource Configuration SDK for Node.js - v2.0.0

### ISSUE THREAD

**Issue by IBMalok** [IBM/ibm-cos-sdk-js-config#11]
## Upcoming release - IBM COS Resource Configuration SDK for Node.js - v2.0.0

We plan to release **ibm-cos-sdk-config - v2.0.0** in October 2022. This issue will be updated with more specifics on timing and the availability of release candidates as we get closer to the release date.

The following information is being provided prior to GA of the release so users can plan on adopting to new sdk - `ibm-cos-sdk-config`.

## Breaking Changes
  - [Changes in Package Imports](#Changes-in-Package-Imports)
  - [Changes in Create Client](#Changes-in-Create-Client)
  - [Changes in API Method Names](#Changes-in-API-Method-Names)
  - [Changes in Response](#Changes-in-Response)
  - [Change in Agent Name](#Change-in-Agent-Name)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------

   ### Changes in Package Imports
   
   | ibm-cos-sdk-config v1.4.1 | ibm-cos-sdk-config v2.0.0 |
   | --- | --- |
   | RC =  require('ibm-cos-sdk-config'); | ResourceConfigurationV1 = require('ibm-cos-sdk-config/resource-configuration/v1'); |
   | | { IamAuthenticator } = require('ibm-cos-sdk-config/auth'); |

   ### Changes in Create Client

   | ibm-cos-sdk-config v1.4.1 | ibm-cos-sdk-config v2.0.0 |
   | --- | --- |
   | const rcConfig = { | const authenticator = new IamAuthenticator({ |
   |     &nbsp; &nbsp; &nbsp; iam_apikey: "Iam_ApiKey", |   &nbsp; &nbsp; &nbsp; apikey: "ApiKey", |
   |     &nbsp; &nbsp; &nbsp; iam_url: "Iam_Url", |   &nbsp; &nbsp; &nbsp; url: "IbmAuthEndpoint", |
   |     &nbsp; &nbsp; &nbsp; url: "URL", |   &nbsp; &nbsp; &nbsp; disableSslVerification: true/false, |
   |     &nbsp; &nbsp; &nbsp; disable_ssl_verification: **true/false** | }); |
   | }; | |
   | rcClient = new RC.ResourceConfigurationV1(rcConfig); | |
   | | const rcConfig = { |
   | |   &nbsp; &nbsp; &nbsp; authenticator: authenticator, |
   | |   &nbsp; &nbsp; &nbsp; serviceUrl: "RcEndPointUrl", |
   | | }; |
   | | rcClient = new ResourceConfigurationV1(rcConfig); |

   ### Changes in API Method Names

   | ibm-cos-sdk-config v1.4.1 | ibm-cos-sdk-config v2.0.0 |
   | --- | --- |
   | activity_tracking | activityTracking |
   | hard_quota | hardQuota |
   | metrics_monitoring | metricsMonitoring |

   ### Changes in Response

   | ibm-cos-sdk-config v1.4.1 | ibm-cos-sdk-config v2.0.0 |
   | --- | --- |
   | Getting response directly for all parameters | Getting response went one level down as response.result |
   | response = await rcClient.getBucketConfig({bucket: bucketName}); | response = await rcClient.getBucketConfig({bucket: bucketName}); |
   | **response**.to.have.property('hard_quota'); | **response.result**.to.have.property('hard_quota'); |
   | &nbsp; &nbsp; | &nbsp; &nbsp; |
   | const response = await rcClient.getBucketConfig({bucket: bucketName }); | const response = await rcClient.getBucketConfig({bucket: bucketName }); |
   | **response**.activity_tracking.read_data_events.to.equal(true/false); | **response.result**.activity_tracking.read_data_events.to.equal(true/false); |
   | **response**.activity_tracking.write_data_events.to.equal(true/false); | **response.result**.activity_tracking.write_data_events.to.equal(true/false); |
   | **response**.activity_tracking.activity_tracker_crn.to.equal(CRN); | **response.result**.activity_tracking.activity_tracker_crn.to.equal(CRN); |
   | &nbsp; &nbsp; | &nbsp; &nbsp; |
   | response = await rcClient.getBucketConfig({bucket: verBucketName}); | response = await rcClient.getBucketConfig({bucket: verBucketName}); |
   | **response**.to.have.property('object_count'); | **response.result**.to.have.property('object_count'); |
   | &nbsp; &nbsp; | &nbsp; &nbsp; |
   | response = await rcClient.getBucketConfig({bucket: bucketName}); | response = await rcClient.getBucketConfig({bucket: bucketName}); |
   | **response**.firewall.to.exist; | **response.result**.firewall.to.exist; |
   | &nbsp; &nbsp; | &nbsp; &nbsp; |
   | response = await rcClient.getBucketConfig({bucket: bucketName}); | response = await rcClient.getBucketConfig({bucket: bucketName}); |
   | **response**.metrics_monitoring.request_metrics_enabled.to.eql(true/false); | **response.result**.metrics_monitoring.request_metrics_enabled.to.eql(true/false); |

  ### Change in Agent Name

  | ibm-cos-sdk-config v1.4.1 | ibm-cos-sdk-config v2.0.0 |
  | --- | --- |
  | ibm-cos-resource-config-sdk-js | ibm-cos-sdk-js-config |

 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
This issue will be used to track features and changes we want to make in the next major release of this package.

**Comment by IBMalok** [comment]
🎉 ibm-cos-sdk-js-config - **v2.0.0** officially been released! 🎉

**Comment by avinash1IBM** [comment]
Closing this as the release was made
